package com.beatus.goodbyeq.utils;

public class Constants {

	public static final String X_FRAME_OPTIONS = "X-Frame-Options";
	public static final String X_FRAME_OPTIONS_VALUE = "DENY";
	public static final String X_XSS_PROTECTION = "X-XSS-Protection";
	public static final String X_XSS_PROTECTION_VALUE = "1; mode=block";
	public static final String STRICT_TRANSPORT_SECURITY = "Strict-Transport-Security";
	public static final String STRICT_TRANSPORT_SECURITY_VALUE = "max-age=16070400; includeSubDomains";
    public static final String URL_PARAM_ACTION = "action";
    public static final String URL_PARAM_ERROR_CODE = "errorCode";
    
    public static final String WEB_PRODUCTS_REQUEST = "/product";
    public static final String WEB_DISTRIBUTOR_REQUEST = "/distributor";
    public static final String WEB_SMS_REQUEST = "/sms";
	public static final String WEB_PRODUCTS_ADD_PRODUCT = "/addProduct";
	public static final String WEB_DISTRIBUTOR_ADD_DISTRIBUTOR = "/addDistributor";
	public static final String WEB_PRODUCTS_GET_PRODUCTS = "/getProducts";
	public static final String WEB_DISTRIBUTOR_GET_DISTRIBUTORS = "/getDistributors";
    public static final String WEB_SMS_SEND_SMS_SCREEN = "/sendsmsScreen";
	public static final String PRODUCT = "product";
	public static final String PRODUCT_NAME = "productName";
	public static final String PRODUCT_CATEGORY = "productCategory";
	public static final String PRODUCT_PRICE = "productPrice";
	public static final String DISTRIBUTOR = "distributor";
	public static final String DISTRIBUTOR_NAME = "distributorName";
	public static final String DISTRIBUTOR_PHONE = "distributorPhone";
	public static final String DISTRIBUTOR_LOCATION = "distributorLocation";
	public static final String DISTRIBUTOR_DISTRICT = "distributorDistrict";
	public static final String PRODUCTS = "Products";
	public static final String REDIRECT = "redirect:";
	public static final String WEB_LOCATION_REQUEST = "/location";
	public static final String WEB_LOCATION_ADD_LOCATION = "/addLocation";
	public static final String WEB_LOCATION_GET_LOCATIONS = "/getLocations";
	public static final String LOCATION = "location";
	public static final String LOCATION_NAME = "locationName";
	public static final String LOCATION_CITY = "locationCity";
	public static final String LOCATION_DISTRICT = "locationDistrict";
	public static final String LOCATION_STATE = "locationState";
	public static final String PRODUCT_LOCATION = "productLocation";
	public static final String WEB_PRODUCTS_ADD_PRODUCT_AND_LOCATION = "/addProductAndLocation";
	public static final String WEB_PRODUCTS_GET_PRODUCTS_AND_LOCATIONS = "/getProductsAndLocations";
	public static final String PRODUCT_LOCATION_NAME = "productandlocation";
	public static final String WEB_LOCATION_EDIT_LOCATION = "/editLocation";
	public static final String WEB_PRODUCTS_EDIT_PRODUCT = "/editProduct";
	public static final String WEB_PRODUCTS_GET_PRODUCT = "/getProduct";
	public static final String WEB_PRODUCTS_EDIT_PRODUCT_AND_LOCATION = "/editProductsAndLocations";
	public static final String WEB_DISTRIBUTOR_EDIT_DISTRIBUTOR = "/editDistributor";
	public static final String WEB_SMS_SEND_SMS_ADD_SCREEN_CONFIGURATION = "/addSmsConfiguration";
	public static final String WEB_SMS_SCREEN_GET_CONFIGURATION = "/getSmsConfiguration";
	public static final String WEB_SMS_SEND_SMS_EDIT_SCREEN_CONFIGURATION = "/editSmsConfiguration";
	public static final String WEB_USER_REQUEST = "/user";
	public static final String WEB_LOGIN = "/login";
	public static final String WEB_USER_SIGNUP = "/signup";
	public static final String AUTHENTICATED = "authenticated";
	public static final String USER_CREATED = "userCreated";
	public static final String ERROR_LOGIN = "There is some problem while login. Please try again";
	public static final String CHAR_SET = "UTF-8";
	public static final String AES = "AES";
	public static final String HMACSHA256 = "HmacSHA256";
	public static final String BILLLIVE_SENDSMS = "billlive-sendsms";
	public static final String ERROR_USER_CREATION = "There is some problem creating the user. Please try again.";
	public static final String USERNAME = "username";
	public static final String WEB_LOGOUT = "/logout";
	public static final String USER = "user";
	public static final String USER_ADMIN = "admin";
	public static final String COMPANY_ID = "companyID";
	public static final String USER_TYPE = "userType";
	public static final String WEB_USER_ADD_COMPANY_USER = "/addCompanyUser";
	public static final CharSequence OK = "OK";
	public static final String WEB_DISTRIBUTOR_DELETE_DISTRIBUTOR = "/deleteDistributor";
	public static final String WEB_LOCATION_DELETE_LOCATION = "/deleteLocation";
	public static final String WEB_PRODUCTS_DELETE_PRODUCTS_AND_LOCATIONS = "/deleteProductsAndLocations";
	public static final String WEB_PRODUCTS_DELETE_PRODUCTS = "/deleteProduct";
    public static final String WEB_GET_BILLS = "/bills";
    public static final String WEB_PRODUCTS_GET_PRODUCT_BY_ID = "/getProductById";
    public static final String FAILURE="N";
    public static final String SUCCESS="Y";
    public static final String NO="NO";
    public static final String SESSION_MODEL = "sessionModel";
    public static final String STORE_ID = "storeID";
    public static final String PROPERTIES_DEV = "properties/application-dev.properties";
    public static final String PROPERTIES_PROD = "properties/application-dev.properties";
    public static final String PROPERTIES_PATH = "properties/application-";
    public static final String PROPERTIES_EXT = ".properties";
    public static final String PROPERTIES_ENV = "${deploy.env}";
    
    public static final String FROM_EMAIL_ADDRESS = "ppavan569@gmail.com";
    
}
